### ISSUE TITLE
Show all worksheets

### ISSUE THREAD

**Issue by Hawkeye1909** [hoogi91/spreadsheets#14]
**Description**  
Could you add the possibility to show all or multiple selected worksheets at once?

**Example**  
I'd like to achieve an excel like view with tabs to switch between the sheets. This ain't possible at the moment (except one uses multiple content elements), right?

**Comment by hoogi91** [comment]
Hey @Hawkeye1909,

you are right about that. The current main scope of the element is always to select something. Either you select a complete sheet or the element is configured to only select certain cells from a worksheet.

But I like your idea to add the ability to just render the complete worksheet information in tabs without selecting anything. I keep this request here up to date until a pull request for this is being created. If you are familiar with developing an own TypoScript DataProcessor and some templating in fluid to do such a job it would be awesome if you find some time to build this possiblity and create a pull request :)

**Comment by hoogi91** [comment]
Hey @Hawkeye1909,

after a long long time there is now a release which comes with the opportunity to enable and use a second content element including the support to show all worksheets of a spreadsheet in tabs.
