### ISSUE TITLE
Backend spreadsheet editor may not be completly initialized in Chrome

### ISSUE THREAD

**Issue by guelzow** [hoogi91/spreadsheets#24]
**Version(s) affected**: 
spreadsheets 2.0.1
charts 1.1.0

**Description**  
When editing a charts record in the backend, the spreadsheets `DataInputElement` is not completey initialized.
The following elements are empty:
`<ul class="nav nav-tabs spreadsheet-sheets" style="display:none;"></ul>`
`<div class="spreadsheet-table" draggable="false" style="display: none"></div>`
This only happens on Chrome, though.

**How to reproduce**  
1.) Install TYPO3 10.4
2.) Install spreadsheets 2.0.1
3.) Install charts 1.1.0
4.) Upload an Excel file
5.) Create a charts record and edit it with Chrome.

It sporadically works, which points to a JS timing problem.

**Possible Solution**  
None so far. I'm still looking into it.

**Additional context**  
Screeshots from the backend and the inspector

![Backend](https://user-images.githubusercontent.com/11192910/85746868-14cf3780-b707-11ea-830d-c5d4cc182045.png)

![Inspector](https://user-images.githubusercontent.com/11192910/85746885-1862be80-b707-11ea-838f-0428b7a72ba4.png)

**Comment by guelzow** [comment]
**What is happening in the code**

The initializing of the sheet rendering is happening here:
https://github.com/hoogi91/spreadsheets/blob/develop/Resources/Private/Assets/JavaScript/main.js#L128

When using it it Chrome, the selector finds only some of the elements.

**Our (dirty) solution**
I've played around a little bit with the events in there. Strangely the typical events like `DOMContentLoaded` and others do not help, not sure why. 

So we simply wait until all three elements can be found. Assuming that there are actually three elements in there.

```javascript

function initSheets () {
    var elements = document.querySelectorAll('.spreadsheet-input-wrap');
    if (elements.length > 2) {
        elements.forEach(element => {
            new SpreadsheetDataInput(element)
        })
    } else {
        setTimeout(initSheets, 300);
    }
}

initSheets();

```

Meh, using a timeout to wait for the DOM to be complete is really suboptimal.

Tobi

**Comment by hoogi91** [comment]
Hey @guelzow,

sorry for my later answer... Would you be so kind to checkout latest "develop" commit (https://github.com/hoogi91/spreadsheets/commit/87b2076e0caf1ff7a9218dd4f292718cca4d36c9) ? This should do the trick and fix issues with not already loaded DOM :)

If that fix works it would be nice to get a short feedback :)

**Comment by guelzow** [comment]
Your fix works like a charm.
I just removed our workaround from our master.


Thanks for fixing   😃 

Tobi
