### ISSUE TITLE
Typo3 V11 issue

### ISSUE THREAD

**Issue by Schnuckel65** [hoogi91/spreadsheets#341]
**Version(s) affected**: 11.5.29

**Description**  
After installing the extension typo3 backend will be unusable and frontend delivers an empty page.
But installing in an typo3 12 (12.4.3) instance works properly.

**How to reproduce**  
Install it on typo3 11 with Bootstrap extension and you will see.

**Possible Solution**  
Do not know.

**Additional context**  
Hope my infos are enough to reproduce the issue.

**Comment by hoogi91** [comment]
Can not be reproduced on a fresh TYPO3 v11 (11.5.39) installation

![image](https://github.com/user-attachments/assets/338e4dc9-34a5-422a-a81b-3262c1474cd8)
![image](https://github.com/user-attachments/assets/264f3b43-f883-4983-8f65-ac29d1ff9344)
![image](https://github.com/user-attachments/assets/639e807e-02e2-40ef-9b27-ae4756640313)
