### ISSUE TITLE
Scrollable tabel with fixed header and row column

### ISSUE THREAD

**Issue by HitTheBeast** [hoogi91/spreadsheets#37]
**Description**  

With large tables especially on mobile devices it is suitable to configure the first row/first column as fix (no scrolling). Any chance to implement?
It would be perfect, if you can define the number of columns/rows to be fixed.
**Example**

**Comment by hoogi91** [comment]
Hey @HitTheBeast,

your wish would result in additional JavaScript to be implemented and this is actually out-of-scope of this extension.
What you can do is changing the page setup in excel to have repeating rows at top of your worksheet. This will be handled and rendered as `<thead>` which you can use in your styling/javascript to be fixed on top when scrolling.

Please follow these steps:
1. Open page setup
2. Select page tab
3. select the rows you want to repeat at top

![image](https://user-images.githubusercontent.com/13648604/126392353-45b81e26-2f7e-46b3-b6bd-e79cd1e3a729.png)
