### ISSUE TITLE
BE TypeError: "DsnValueObject::getSheetIndex() must be of the type int, null returned"

### ISSUE THREAD

**Issue by mcsikos-udg** [hoogi91/spreadsheets#38]
Hi hoogie91, vte-udg asked me to contact you about an update problem. 

We have updated spreadsheets from 1.1.2 to 2.0.2 in a TYPO3 10.4.17. We are now experiencing the following problem:

**Version(s) affected**: 
2.0.2

**Description**  
Return value of Hoogi91\Spreadsheets\Domain\ValueObject\DsnValueObject::getSheetIndex() must be of the type int, null returned

**How to reproduce**  
Call a BE-Page with a spreadsheed content element

**Possible Solution**  
in legacyDSNParsing() is a condition
if (empty($fullSelection) === false) {...}

Here, $fullSelection is " '0' (1 chars) ", so the "empty($fullSelection)" will be "true".
As a result, it cannot be executed:
"
            $this->sheetIndex = (int)($sheetIndex ?: 0);
            $this->selection = $selection ?: null;
            $this->directionOfSelection = $directionOfSelection ?: null;
"
which leads to a " $this->sheetIndex" is "null"

Maybe you can fix this?

Best of wishes 

mcsikos

**Comment by hoogi91** [comment]
Hey @mcsikos-udg, please check again on feature branch #40 as I now added some new test cases :)
