### ISSUE TITLE
Select the first or only table while saving the first time. 

### ISSUE THREAD

**Issue by stephangrass** [hoogi91/spreadsheets#44]
Hi, I've got a question.

After you have uploaded an Excel file, you have to select the table via the spreadsheetInput. Is it possible somehow to automatically select the first table? Or if there is only one table, it is this one.

I have an import (external_import) of product data with Excel tables, which should be output via this great extension. It would be useful if the first table were selected immediately during saving.

Stephan

**Comment by hoogi91** [comment]
Introduced with #48
