### ISSUE TITLE
Rowspan breaks table

### ISSUE THREAD

**Issue by mcsikos-udg** [hoogi91/spreadsheets#46]
**Version(s) affected**: 
2.0.2

**Description**  
Hi hoogie91, we are having problems displaying merged rows here.

Attached are also some screenshots to make it clearer.

When rows are merged, a rowspan is rendered in the fluid. When this is the case, the table is displayed incorrectly in the front-end.

In the old version of the spreadsheets (1.0.2), however, no rowspan is output with the same Excel and the display was correct.

Do you know what the reason could be?

**Additional context**  
![spreadsheets-11](https://user-images.githubusercontent.com/86838295/130616662-69163606-3a24-4478-9cfe-a72e88fd49e0.png)
![spreadsheets-10](https://user-images.githubusercontent.com/86838295/130616665-a046b085-240e-40c6-b3ac-5969d6fb7574.png)

**Comment by vte-udg** [comment]
The reason seems to be that rows 2 and 3 are actually empty and get stripped, thus the rowspan="3" accidentally affects row 4 and 5.

**Comment by hoogi91** [comment]
Fixed with #49
