### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by Wallma2** [hoogi91/spreadsheets#47]
Version: 2.0.2**Version(s) affected**: x.y.z

If an Excel spreadsheets is sorted by date and the date in the format e.g dd.mm.yyyy it will changed in typo 3 10 to the following format: mm.dd.yyyy. This is not desired if it is done on a  German Homepage.

Regards

Wallma

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by hoogi91** [comment]
Hey @Wallma2,

sorry but this is at the moment not fixable for me in scope of this extension. Please have a look at:
https://stackoverflow.com/questions/34900605/excel-cell-style-issue

It shows/explains that currently the problem relies on how Excel saves it's date values. For your described case I guess that the "numFmtId" attribute has the value 14. That one is currently automatically formatted by the underlying phpoffice/phpspreadsheet extension to m/d/yyyy (see https://github.com/PHPOffice/PhpSpreadsheet/blob/master/src/PhpSpreadsheet/Style/NumberFormat.php#L267)

The reason why excel shows german date formatting relies to OS region settings. Inside region settings the date format can be selected for short/long outputs and much more:
<img src="https://user-images.githubusercontent.com/13648604/132410913-74023630-4e97-441b-a729-851506e7547f.png" width="250"/>

Unfortunately there is no easy way to define how the default date format with ID 14 should look like in all the different languages. Therefore my advice would be to convert/format the date fields into text field values with `=TEXT(A2;"dd.MM.yyyy")` see the example:
[date_convert.xlsx](https://github.com/hoogi91/spreadsheets/files/7124388/date_convert.xlsx)
Note that the converted text column may look different in excel but the outcome in your website should be correct
