### ISSUE TITLE
Undefined array key "size" in Classes/Form/Element/DataInputElement.php line 49

### ISSUE THREAD

**Issue by guelzow** [hoogi91/spreadsheets#539]
Hi everyone.

**Version(s) affected**:
4.0.0

**Description**  
PHP Warning: Undefined array key "size" in Classes/Form/Element/DataInputElement.php line 49
[To the source code](https://github.com/hoogi91/spreadsheets/blob/4.0.0/Classes/Form/Element/DataInputElement.php#L49)

**How to reproduce**  
1. Setup TYPO3 12 lts with PHP 8.2
2. Switch to debug mode
3. Go to the backend and create a new record

**Possible Solution**  
Change this line to:
```php
$this->view->assign('inputSize', (int)($this->config['size'] ?? 0));
```

**Additional context**  
n/a

Tobi

**Comment by hoogi91** [comment]
Solved with Release [4.0.1](https://github.com/hoogi91/spreadsheets/releases/tag/4.0.1)
