### ISSUE TITLE
tables headers 

### ISSUE THREAD

**Issue by bj0hn** [hoogi91/spreadsheets#58]
Hi Thorsten, 

I came across your spreadsheets extension through your update and tested it briefly. Really nice!

Very nice is the selection of table cells in the backend. 

What I didn't manage to do is to output the headers of a tables. Is there a way to do this? 

Then I got the idea, wouldn't it be cool if you could mark <td> and <th> cells, as you can also do with the area?

Alternatively, an option "Table header position" with none/top/left like the content element tables hast, would be nice.

**Comment by hoogi91** [comment]
Hey @bj0hn,

thanks for your input. There is already a way to render a table with <thead>. 
It can be achieved by following screenshot - see also https://github.com/hoogi91/spreadsheets/issues/37#issuecomment-883695181
<img src="https://user-images.githubusercontent.com/13648604/126392353-45b81e26-2f7e-46b3-b6bd-e79cd1e3a729.png" width="200"/>

Nevertheless I already wrote a first implementation of using the "Table header position" and "Use table footer" options from default table content element. That can be found in feature branch "feature/more-table-options" (https://github.com/hoogi91/spreadsheets/commit/1a3dee091dd1225352173230dc04828e2c350f8d) which needs a bit more love in testing and documentation. Maybe I can do that on the weekend :)

**Comment by hoogi91** [comment]
Hey @bj0hn,

the new release https://github.com/hoogi91/spreadsheets/releases/tag/3.2.0 now contains same options as TYPO3's default table content element. Those are applied when the spreadsheet table does not have head data as described above.

Hope that this implementation satisfy your needs now :)

**Comment by bj0hn** [comment]
Supercool, thanks. I will test it.

**Comment by bj0hn** [comment]
Have tried it, works wonderfully :)

One thing I noticed though inside the` <thead>` should be used `<th>` rather than` <td>`.

Example: 

```
<table>
    <caption>Council budget (in £) 2018</caption>
    <thead>
        <tr>
            <th scope="col">Items</th>
            <th scope="col">Expenditure</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">Donuts</th>
            <td>3,000</td>
        </tr>
        <tr>
            <th scope="row">Stationery</th>
            <td>18,000</td>
        </tr>
    </tbody>
</table>

```
Source : https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead

The html is valid, but for accessibility `<th>` are nicer :)
