### ISSUE TITLE
Update to 4.0.1 or 4.0.2 on TYPO3 11 will cause Fatal error

### ISSUE THREAD

**Issue by stephangrass** [hoogi91/spreadsheets#610]
I will get this error after Update to 4.0.1 or 4.0.2 from 4.0.0 under TYPO3 11:

Fatal error: Declaration of TYPO3\CMS\Core\Http\Uri::getScheme() must be compatible with Psr\Http\Message\UriInterface::getScheme(): string in /www/htdocs/w018b32c/typo3_src-11.5.37/typo3/sysext/core/Classes/Http/Uri.php on line 174

**Comment by hoogi91** [comment]
Hey @stephangrass,

I can not see a relation between the update of this extension and the issue. 
Looks like your dependency update was requesting a newer version of "psr/http-message" which defines the UriInterface as described and together with the installed TYPO3 version 11.5.37 (https://github.com/TYPO3/typo3/blob/v11.5.37/typo3/sysext/core/Classes/Http/Uri.php#L174) this does not work.

How did you install the extension? This should not happen when using Composer as in TYPO3 install the constraint is "psr/http-message:^1.0" which should prevent installing the newer version of this interface.

Please note that I can not support/address those issues in TER installations :)
