### ISSUE TITLE
Clear renderType spreadsheetInput

### ISSUE THREAD

**Issue by stephangrass** [hoogi91/spreadsheets#62]
Hi,
Is it possible to delete an already occupied field 'spreadsheetInput'? Unfortunately, clicking on the button to the right of the field has no effect.

![2022-02-23_14-44-48](https://user-images.githubusercontent.com/4489147/155332259-424ef9d6-06a5-46fb-b180-2a0d0aa660bf.jpg)

Thanks
Stephan

**Comment by hoogi91** [comment]
Hey @stephangrass,

this functionality is currently only there to allow a reset of the field to it's old value.
I just added a new functionality to also unset the input completely as can be seen in commit https://github.com/hoogi91/spreadsheets/commit/11cbea6f650d5b73fae7675874c273b97b6b573d
Just checkout the latest release [3.3.0](https://github.com/hoogi91/spreadsheets/releases/tag/3.3.0) to use that functionality 😄
