### ISSUE TITLE
Layout issues in TYPO3 8 Backend

### ISSUE THREAD

**Issue by imminger** [hoogi91/spreadsheets#9]
**Version(s) affected**: Charts 1.0.5 | TYPO3 8.7.29

**Description**  
Tables are not scrollable and the checkboxes are not displayed
![Charts](https://user-images.githubusercontent.com/15834641/70545385-c5138f00-1b6d-11ea-889a-89d0a10e5911.png)

**How to reproduce**  
1. Create new diagram in list view
2. Use Excel file with more than 10 rows

**Possible Solution**  

**Additional context**  

I only tested with TYPO3 8.
Extension is awesome otherwise 🎉

**Comment by hoogi91** [comment]
Hey @imminger,

thanks for your report. I moved it to the spreadsheet project cause it is related to this extension.
I fixed the missing checkbox issue in #10. Can you confirm that this fixes the display of the checkbox for you?

Regarding the table scrolling:
Can you please give me more information about your environment? I could not reproduce the issue in latest Chrome, FF (Windows and Linux/Ubuntu) and Edge. If you can provide me your OS, Browser and Version I will try to figure that out.
Currently the wrapper around https://handsontable.com/ is disabling scrolling with "overflow:hidden" and only HandsOnTable itself will handling the existence of scrollbars inside the wrapper.

Thanks for your help :)

**Comment by imminger** [comment]
Hi, 

the checkboxes now work correctly. Thanks!

Scrolling issue: it seems to work now. I use Chrome on macOS. Not sure what caused the issue earlier. Sorry.

Thank you for developing this extensions!

**Comment by hoogi91** [comment]
Hi @imminger,

the new version has now been released. I was not sure wether everything worked correctly cause the deployment routine on travis-ci failed while uploading to TYPO3 ter... but now it seems that it finally arrived there https://extensions.typo3.org/extension/spreadsheets

Thanks for your contribution :)
